[package]
name = "updater"
version = "0.1.0"
authors = ["Csányi István <icsanyi96@gmail.com>"]
edition = "2018"
publish = false
repository = "https://github.com/AmionSky/updater"
license = "MIT"
maintenance = { status = "experimental" }

[dependencies]
simple_logger = { version = "1.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0" }
toml = "0.5"
log = "0.4"
fs2 = "0.4"
semver = "0.9"
ureq = "0.11"
regex = "1.3"
lazy_static = "1.4"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false