[package]
name = "updater"
version = "0.1.0"
authors = ["Csányi István <icsanyi96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = { version = "1.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
log = "0.4"
fs2 = "0.4"
semver = "0.9"