name: Create release and upload built executables

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            setup: sudo apt-get install libgtk-3-dev
            target: x86_64-unknown-linux-gnu
            exename: updater-linux-x64
            rename: mv updater-bin
            asset: linux-x64
          - os: windows-latest
            setup: echo OK
            target: x86_64-pc-windows-msvc
            exename: updater-win-x64.exe
            rename: ren updater-bin.exe
            asset: win-x64
    name: Build ${{ matrix.exename }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Setup
        run: ${{ matrix.setup }}
      - name: Update Rust
        run: rustup update
      - name: Install targets
        run: rustup target install ${{ matrix.target }}
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release
      - name: Run tests
        run: cargo test --target ${{ matrix.target }} --release
      - name: Rename executable
        run: |
          cd target/${{ matrix.target }}/release
          ${{ matrix.rename }} ${{ matrix.exename }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset }}
          path: target/${{ matrix.target }}/release/${{ matrix.exename }}

  create:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Updater ${{ github.ref }}
          draft: false
          prerelease: false

  upload:
    strategy:
      matrix:
        include:
          - asset: linux-x64
            target: updater-linux-x64
            mime: application/octet-stream
          - asset: win-x64
            target: updater-win-x64.exe
            mime: application/vnd.microsoft.portable-executable
    name: Upload ${{ matrix.target }} to Release
    runs-on: ubuntu-latest
    needs: [create]
    steps:
      - name: Download ${{ matrix.asset }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.asset }}
      - name: Get the upload URL for a release
        uses: bruceadams/get-release@v1.2.0
        id: get_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload ${{ matrix.asset }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ matrix.target }}
          asset_name: ${{ matrix.target }}
          asset_content_type: ${{ matrix.mime }}
